// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsKdP0Ajuj9FzbFAeCp7EAgOSgLheT5P8',
    appId: '1:246517716169:web:870c8b8e1f6c345067e918',
    messagingSenderId: '246517716169',
    projectId: 'kugentica-84e4d',
    authDomain: 'kugentica-84e4d.firebaseapp.com',
    storageBucket: 'kugentica-84e4d.firebasestorage.app',
    measurementId: 'G-BQ5HRCFJ18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg3bi5BNOWGFhcxSAatcIz5B1cjzjOpos',
    appId: '1:246517716169:android:cda8c0bb61151ae867e918',
    messagingSenderId: '246517716169',
    projectId: 'kugentica-84e4d',
    storageBucket: 'kugentica-84e4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu9L5cpqFQ_MKIS2VmTk9mG_zubDTXNYc',
    appId: '1:246517716169:ios:ee519e14e3cfe9c567e918',
    messagingSenderId: '246517716169',
    projectId: 'kugentica-84e4d',
    storageBucket: 'kugentica-84e4d.firebasestorage.app',
    iosBundleId: 'com.example.calenderBookmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu9L5cpqFQ_MKIS2VmTk9mG_zubDTXNYc',
    appId: '1:246517716169:ios:ee519e14e3cfe9c567e918',
    messagingSenderId: '246517716169',
    projectId: 'kugentica-84e4d',
    storageBucket: 'kugentica-84e4d.firebasestorage.app',
    iosBundleId: 'com.example.calenderBookmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsKdP0Ajuj9FzbFAeCp7EAgOSgLheT5P8',
    appId: '1:246517716169:web:e9382ce85dffb95467e918',
    messagingSenderId: '246517716169',
    projectId: 'kugentica-84e4d',
    authDomain: 'kugentica-84e4d.firebaseapp.com',
    storageBucket: 'kugentica-84e4d.firebasestorage.app',
    measurementId: 'G-6DX6FLX4RV',
  );

}